apiVersion: charts.my.domain/v1alpha1
kind: VisitorsHelm
metadata:
  name: visitorshelm-sample
spec:
  # Default values copied from <project_dir>/helm-charts/visitors-helm/values.yaml
  backend:
    size: 1
  frontend:
    title: Helm Installed Visitors Site
  
  
