# permissions for end users to edit visitorshelms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: visitorshelm-editor-role
rules:
- apiGroups:
  - charts.my.domain
  resources:
  - visitorshelms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.my.domain
  resources:
  - visitorshelms/status
  verbs:
  - get
