# permissions for end users to view visitorshelms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: visitorshelm-viewer-role
rules:
- apiGroups:
  - charts.my.domain
  resources:
  - visitorshelms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.my.domain
  resources:
  - visitorshelms/status
  verbs:
  - get
